# Generated by Django 5.0.2 on 2024-02-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
    ]
